/**
 * Single source of truth for the 20 authority articles (slugs, titles, SEO).
 * Used by generate-articles.js and patch-index-authority.js.
 */
const ARTICLES = [
  { slug: 'ultimate-moringa-encyclopedia', title: 'The Ultimate Moringa Encyclopedia (History to Modern Science)', description: 'Complete encyclopedia of Moringa oleifera: origins, traditional use, plant parts, nutrition, research context, and how India fits into global supply.', h1: 'The Ultimate Moringa Encyclopedia', lead: 'From ancient kitchens to modern labs — a single reference for what Moringa is, why it matters, and how to think critically about claims.' },
  { slug: 'moringa-benefits-every-age', title: 'Moringa Benefits for Every Age: Kids, Adults & Seniors', description: 'Age-by-age guide to Moringa nutrition, sensible serving ideas, and safety considerations for children, adults, and older adults.', h1: 'Moringa Benefits for Every Age', lead: 'How different life stages change nutrition needs — and where Moringa fits as food, not magic.' },
  { slug: 'moringa-side-effects-safety', title: 'Moringa Side Effects & Safety: What the Evidence Actually Says', description: 'Honest guide to Moringa safety, drug interactions, pregnancy and breastfeeding cautions, and when to stop and talk to a clinician.', h1: 'Moringa Side Effects & Safety', lead: 'The most searched topic deserves straight answers, medical disclaimers, and zero fear-mongering.' },
  { slug: 'pure-vs-adulterated-moringa', title: 'How to Identify Pure vs. Adulterated Moringa Powder', description: 'Sensory checks, lab tests, certificate review, and red flags that separate genuine leaf powder from fillers and low-grade blends.', h1: 'Pure vs. Adulterated Moringa', lead: 'Trust is built on verification — here is a practical buyer and consumer checklist.' },
  { slug: 'moringa-vs-spirulina', title: 'Moringa vs. Spirulina: Green Superfood Comparison', description: 'Compare Moringa leaf powder with spirulina on origin, nutrition profile, taste, use cases, and which to choose for your goals.', h1: 'Moringa vs. Spirulina', lead: 'Two different organisms, two different stories — pick with context, not hype.' },
  { slug: 'moringa-vs-kale-spinach', title: 'Moringa vs. Kale vs. Spinach: Nutrition Density Compared', description: 'Leafy greens versus dried Moringa powder — how serving size skews comparisons and what "density" really means on your plate.', h1: 'Moringa vs. Kale vs. Spinach', lead: 'Why apples-to-apples comparisons matter, and when Moringa wins on convenience.' },
  { slug: 'moringa-powder-vs-capsules', title: 'Moringa Powder vs. Capsules: Absorption & Convenience', description: 'Bioavailability basics, excipients in capsules, cost per gram, and how to choose powder or capsules for consistency and lifestyle.', h1: 'Moringa Powder vs. Capsules', lead: 'Same plant, different delivery — match the format to your routine and digestion.' },
  { slug: 'organic-india-vs-vahdam-vs-kuli-kuli', title: 'Organic India vs. Vahdam vs. Kuli Kuli: Brand Comparison', description: 'Three-way comparison of popular Amazon Moringa brands — positioning, formats, sourcing story, and who each line suits best.', h1: 'Organic India vs. Vahdam vs. Kuli Kuli', lead: 'No single "winner" — choose by certification appetite, taste, and product format.' },
  { slug: 'moringa-weight-loss', title: 'Moringa for Weight Loss: Metabolism & Science-Backed Context', description: 'What research suggests about Moringa, blood sugar stability, inflammation, and weight management — without miracle promises.', h1: 'Moringa for Weight Loss', lead: 'Supportive habits first; Moringa may be a helpful adjunct within a real food plan.' },
  { slug: 'moringa-diabetes', title: 'Moringa for Diabetes Management: Blood Sugar & Medical Disclaimers', description: 'Evidence overview on Moringa and glycemic control, medication interactions, and why this is education — not treatment advice.', h1: 'Moringa & Blood Sugar (Diabetes Context)', lead: 'Read this alongside your doctor or diabetes educator, not instead of them.' },
  { slug: 'moringa-hair-skin', title: 'Moringa for Hair Growth & Skin Glow: Beauty Angle Explained', description: 'Nutrients in Moringa linked to skin and hair health, topical vs. oral use, realistic timelines, and product types worth exploring.', h1: 'Moringa for Hair & Skin', lead: 'Beauty keywords meet biology — set expectations and avoid overnight-miracle marketing.' },
  { slug: 'moringa-anemia', title: 'Moringa for Anemia: Iron, Hemoglobin & Diet Pairings', description: 'Non-heme iron in Moringa leaves, absorption enhancers (vitamin C), and limits compared to clinical iron therapy.', h1: 'Moringa for Anemia Support', lead: 'Food diversity plus medical care when iron deficiency is diagnosed.' },
  { slug: 'moringa-export-quality-standards', title: 'Moringa Export Quality: HACCP, ISO & Organic Certifications', description: 'What global buyers ask for — HACCP, ISO 22000, GMP, organic schemes (USDA, EU, NPOP), and how they reduce risk in the supply chain.', h1: 'Moringa Export Quality Standards', lead: 'Certifications are shorthand for systems — here is what each acronym implies in practice.' },
  { slug: 'top-moringa-states-india', title: 'Top Moringa Producing States in India (Data-Heavy Overview)', description: 'Regional production clusters, climate fit, processing hubs, and why state-level data is only one slice of sourcing decisions.', h1: 'Top Moringa States in India', lead: 'Geography, infrastructure, and certificates together beat a single ranking table.' },
  { slug: 'moringa-packaging-international', title: 'Packaging Moringa for International Markets: Moisture & Shelf Life', description: 'Barrier films, desiccants, modified atmosphere, labeling for EU/US, and moisture control to prevent mold and rancidity.', h1: 'Moringa Packaging for Export', lead: 'Shelf life is won or lost in the first 48 hours after drying — packaging locks in the win.' },
  { slug: 'moringa-eu-market', title: 'Moringa in the European Union: Trends, Novel Food & Regulations', description: 'EU market outlook for Moringa ingredients, regulatory themes, labeling, and what Indian exporters should validate with legal counsel.', h1: 'Moringa & the EU Market', lead: 'Trends are promising — compliance is non-negotiable.' },
  { slug: 'moringa-cooking-daily', title: '10+ Creative Ways to Use Moringa in Daily Cooking', description: 'Indian and Western recipes, heat stability tips, flavor masking, and dose ideas for smoothies, dals, rotis, and baked goods.', h1: 'Moringa in Daily Cooking', lead: 'Make Moringa a habit by hiding it in food you already love.' },
  { slug: 'moringa-detox-tea-recipes', title: 'Moringa Detox Tea Recipes: Morning Rituals Without False Claims', description: 'Tea blends, steeping notes, and honest language around "detox" — hydration and polyphenols, not toxin removal fiction.', h1: 'Moringa Detox Tea Recipes', lead: 'Rituals support consistency; science supports moderation and sleep.' },
  { slug: 'diy-moringa-face-masks', title: 'DIY Moringa Face Masks for Acne-Prone Skin (Patch Test First)', description: 'Simple mask bases, why patch tests matter, when to see a dermatologist, and how Moringa powder behaves on sensitive skin.', h1: 'DIY Moringa Face Masks', lead: 'Kitchen skincare can be fun — respect your skin barrier first.' },
  { slug: 'moringa-for-pets', title: 'Moringa for Pets: Safe Dosing for Dogs & Cats', description: 'Veterinary caution, tiny amounts, toxic plants to avoid confusing with Moringa, and why commercial pet foods already balance micronutrients.', h1: 'Moringa for Dogs & Cats', lead: 'If in doubt, ask your vet before supplementing animals.' },
];

module.exports = { ARTICLES };
